services:
  mongodb:
    image: mongo:8.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-vol:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
networks:
  default:
    driver: bridge
volumes:
  mongodb-vol: